config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # root
  root "videos#show_video"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'videos#show_video'

  resources :videos
  scope "/videos" do
    post "mark-video-as-marked", to: 'videos#mark_video_as_viewed_json'
    post "show-random-video", to: 'videos#show_random_video_json'
  end

  resources :genres
end

app/models/genre.rb
class Genre
  include Mongoid::Document

  field :name, type: String
  field :description, type: String

  has_many :videos
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :authenticate_user!
  def new
    if current_user.is_admin
      @genre = Genre.new

      render "new"
    else
      redirect_to root_url, :alert => "Sorry, but you don't have the access to this page"
    end
  end

  def create
    if current_user.is_admin
      @genre = Genre.new(genre_params)
      if @genre.save
        redirect_to genres_path
      else
        # This line overrides the default rendering behavior, which
        # would have been to render the "create" view.
        redirect_to new_genre_path, :alert => "Sorry, there is a problem"
      end
    else
      redirect_to root_url, :alert => "Sorry, but you don't have the access to this page"
    end
  end

  def update
    if current_user.is_admin
      @genre = Genre.find(params[:id])
      if @genre.update_attributes(genre_params)
        redirect_to genres_path
      else
        render 'edit'
      end
      render "new"
    else
      redirect_to root_url, :alert => "Sorry, but you don't have the access to this page"
    end

  end

  def edit
    if current_user.is_admin
      @genre = Genre.find(params[:id])

      render "edit"
    else
      redirect_to root_url, :alert => "Sorry, but you don't have the access to this page"
    end
  end

  def destroy
    if current_user.is_admin
      @genre = Genre.find(params[:id])
      if @genre.destroy
        redirect_to videos_path, :alert => "Genre delete is successful"
      else
        redirect_to videos_path, :alert => "Sorry, there is a problem with deleting this genre"
      end
    else
      redirect_to root_url, :alert => "Sorry, but you don't have the access to this page"
    end
  end

  def index
    @genres = Genre.all

    render "index"
  end

  def show
    if current_user.is_admin
      @genre = Genre.find(params[:id])

      render "show"
    else
      redirect_to root_url, :alert => "Sorry, but you don't have the access to this page"
    end
  end

  private
    def genre_params
      params.require(:genre).permit(:name, :description)
    end
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/views/genres/_form.html.erb
<%= form_for @genre do |f| %>
  <div class="form-group">
    <%= f.label(:name) %>
    <%= f.text_field(:name, class: "form-control") %>
  </div>
  <div class="form-group">
    <%= f.label(:description) %>
    <%= f.text_field(:description, class: "form-control") %>
  </div>
  <div class="form-group">
    <%= f.submit("Submit", class: "btn btn-primary") %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<div class="col-lg-12">
  <h1>Update "<%= @genre.name %>" genre (ID: <%= @genre._id %>)</h1>
  <%= render "genres/form" %>
</div>

app/views/genres/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Genres</h1>
  </div>
  <div class="col-lg-4 col-lg-offset-8 pull-right">
    <%= link_to "Add a genre", new_genre_path, class: "btn btn-success"  %>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <table class="datatable">
      <thead>
        <tr>
          <td>ID</td>
          <td>Name</td>
          <td>Description</td>
          <td>Actions</td>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <td>ID</td>
          <td>Name</td>
          <td>Description</td>
          <td>Actions</td>
        </tr>
      </tfoot>
      <tbody>
        <% @genres.each do |g| %>
          <tr>
            <td><%= g.id %></td>
            <td><%= g.name %></td>
            <td><%= g.description %></td>
            <td><%= link_to "Show", genre_path(g), class: "btn btn-warning" %><%= link_to "Delete", genre_path(g), method: :delete, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/genres/new.html.erb
<div class="col-lg-12">
  <h1>Add new Video</h1>
  <%= render "genres/form" %>
</div>

app/views/genres/show.html.erb
<div class="col-lg-12">
  <h1>Genre <%= @genre.name %></h1>
  <div class="row">
    <div class="col-lg-3">
      <b>ID:</b>
    </div>
    <div class="col-lg-9">
      <p><%= @genre._id %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-3">
      <b>Name:</b>
    </div>
    <div class="col-lg-9">
      <p><%= @genre.name %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-3">
      <b>Description:</b>
    </div>
    <div class="col-lg-9">
      <p><%= @genre.description %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <%= link_to "Edit", edit_genre_path(@genre), class: "btn btn-warning" %>  <%= link_to "Delete", genre_path(@genre), method: :delete, class: "btn btn-danger" %>
    </div>
  </div>
</div>