config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # root
  root "videos#show_video"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'videos#show_video'

  resources :videos
  scope "/videos" do
    post "mark-video-as-marked", to: 'videos#mark_video_as_viewed_json'
    post "show-random-video", to: 'videos#show_random_video_json'
  end

  resources :genres
end

app/views/shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Alex test app</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if current_user.is_admin %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administration <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Videos", videos_path  %></li>
              <li><%= link_to "Genres", genres_path  %></li>
            </ul>
          </li>
          <% end %>
          <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete  %> </li>
        <% else %>
          <li> <%= link_to "Sign In", new_user_session_path  %> </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>